# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\张宇涛\Downloads\exercise3_implement\zju_igem_software_assignment-I-_exercise3_implement\ui\octopus_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(320, 30, 131, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 70, 401, 171))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 250, 401, 31))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(180, 290, 401, 171))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionquit = QtWidgets.QAction(MainWindow)
        self.actionquit.setObjectName("actionquit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.action_Close = QtWidgets.QAction(MainWindow)
        self.action_Close.setObjectName("action_Close")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.action_savs_in_the_same_file = QtWidgets.QAction(MainWindow)
        self.action_savs_in_the_same_file.setObjectName("action_savs_in_the_same_file")
        self.actionsave_in_another_file = QtWidgets.QAction(MainWindow)
        self.actionsave_in_another_file.setObjectName("actionsave_in_another_file")
        self.actionsave_the_completed_sequence = QtWidgets.QAction(MainWindow)
        self.actionsave_the_completed_sequence.setObjectName("actionsave_the_completed_sequence")
        self.menuSave.addAction(self.action_savs_in_the_same_file)
        self.menuSave.addAction(self.actionsave_in_another_file)
        self.menuSave.addAction(self.actionsave_the_completed_sequence)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.action_Close)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuQuit.addAction(self.actionquit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuQuit.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.action_Close)
        self.toolBar.addAction(self.actionquit)
        self.toolBar.addAction(self.actionHelp)

        self.retranslateUi(MainWindow)
        self.actionquit.triggered.connect(MainWindow.close) # type: ignore
        self.actionHelp.triggered.connect(MainWindow.trigger_actHelp) # type: ignore
        self.actionOpen.triggered.connect(MainWindow.trigger_actOpen) # type: ignore
        self.action_Close.triggered.connect(MainWindow.trigger_actClose) # type: ignore
        self.pushButton.clicked.connect(MainWindow.send_sequence_to_LLM) # type: ignore
        self.action_savs_in_the_same_file.triggered.connect(MainWindow.save) # type: ignore
        self.actionsave_in_another_file.triggered.connect(MainWindow.save_as) # type: ignore
        self.actionsave_the_completed_sequence.triggered.connect(MainWindow.save_the_completed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Octopus Editor v0.0.1"))
        self.pushButton.setText(_translate("MainWindow", "send sequence to ProtBERT"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionquit.setText(_translate("MainWindow", "Quit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.action_Close.setText(_translate("MainWindow", "Close"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.action_savs_in_the_same_file.setText(_translate("MainWindow", "save"))
        self.actionsave_in_another_file.setText(_translate("MainWindow", "save as"))
        self.actionsave_the_completed_sequence.setText(_translate("MainWindow", "save the completed sequence"))
